### ISSUE TITLE
off grid

### ISSUE THREAD

**Issue by jamiejcross** [Mehrpouya/off-the-grid#4]
1) remove sound from all video
2) remove duplicate picture from Sunday
3) add medical web photo, sent to hadi 
4) make password protected 

5) MAKE high quality PDF print of each page

**Comment by Mehrpouya** [comment]
All done, let me know how would you like the pdf? at the moment all the pictures are in our dropbox eiggmap visualisation/pdfs/day-of-the-week

**Comment by jamiejcross** [comment]
Can you now follow up with the outstanding issue regarding the migration of the Wordpress Blog.

Jamie
